version: '3'
services:
  frontend:
    image: ghcr.io/buildbarn/bb-storage:20250408T112116Z-1d733a3
    command:
    - /config/frontend.jsonnet
    expose:
    - 9980
    ports:
    - 8980:8980
    volumes:
    - ./config:/config

  storage-0:
    image: ghcr.io/buildbarn/bb-storage:20250408T112116Z-1d733a3
    command:
    - /config/storage.jsonnet
    expose:
    - 8981
    - 9980
    volumes:
    - ./config:/config
    - ./volumes/storage-ac-0:/storage-ac
    - ./volumes/storage-cas-0:/storage-cas

  storage-1:
    image: ghcr.io/buildbarn/bb-storage:20250408T112116Z-1d733a3
    command:
    - /config/storage.jsonnet
    expose:
    - 8981
    - 9980
    volumes:
    - ./config:/config
    - ./volumes/storage-ac-1:/storage-ac
    - ./volumes/storage-cas-1:/storage-cas

  scheduler:
    image: ghcr.io/buildbarn/bb-scheduler:20250411T124310Z-1c726bd
    command:
    - /config/scheduler.jsonnet
    expose:
    - 8982
    - 8983
    - 8984
    - 9980
    ports:
    - 7982:7982
    - 8983:8983
    - 8984:8984
    volumes:
    - ./config:/config

  browser:
    image: ghcr.io/buildbarn/bb-browser:20250414T180739Z-9b44996
    command:
    - /config/browser.jsonnet
    expose:
    - 9980
    ports:
    - 7984:7984
    volumes:
    - ./config:/config

  runner-installer:
    image: ghcr.io/buildbarn/bb-runner-installer:20250411T124310Z-1c726bd
    volumes:
    - ./volumes/bb:/bb

  # The FUSE worker is the most efficient configuration.
  worker-fuse-ubuntu22-04:
    image: ghcr.io/buildbarn/bb-worker:20250411T124310Z-1c726bd
    command:
    - /config/worker-fuse-ubuntu22-04.jsonnet
    # Need to be privileged for the FUSE mounting to work.
    privileged: true
    volumes:
    - ./config:/config
    - type: bind
      source: ./volumes/worker-fuse-ubuntu22-04
      target: /worker
      bind:
        # Bidirectional mount to expose the FUSE mount.
        propagation: shared

  runner-fuse-ubuntu22-04:
    image: ghcr.io/catthehacker/ubuntu:act-22.04@sha256:5f9c35c25db1d51a8ddaae5c0ba8d3c163c5e9a4a6cc97acd409ac7eae239448
    command:
    - sh
    - -c
    - while ! test -f /bb/installed; do sleep 1; done; exec /bb/tini -v -- /bb/bb_runner /config/runner-ubuntu22-04.jsonnet
    network_mode: none
    volumes:
    - ./config:/config
    - ./volumes/bb:/bb
    - type: bind
      source: ./volumes/worker-fuse-ubuntu22-04
      target: /worker
      bind:
        # HostToContainer mount to use the FUSE mount.
        propagation: slave
    depends_on:
    - runner-installer


  portal-frontend:
    image: ghcr.io/buildbarn/bb-portal-frontend:cd933190e49a48f6ba41a7410408f77aef471e47
    volumes:
    - ./config:/config
    depends_on:
    - portal-backend
    expose:
    - 3000
    ports:
    - 3000:3000
    environment:
      - NEXT_PUBLIC_BROWSER_URL=http://worker01-node.rdavletov.crpt.cloud:7984
      - NEXT_PUBLIC_BES_BACKEND_URL=http://worker01-node.rdavletov.crpt.cloud:8081
      - NEXT_PUBLIC_BES_GRPC_BACKEND_URL=grpc://worker01-node.rdavletov.crpt.cloud:8082

  portal-backend:
    image: ghcr.io/buildbarn/bb-portal-backend:20250610t154514z-b494d88
    command: 
    - --config-file=/config/portal.jsonnet
    volumes:
    - ./config:/config
    expose:
    - 8081
    - 8082
    ports:
    - 8081:8081
    - 8082:8082
